config/routes.rb
Testapp::Application.routes.draw do
  get "user/index"
  get "user/show"
  get "comments/new"
  get "posts/index"
  get "welcome/index"
  
  devise_for :users
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
    end

  resources :users
  resources :welcome
  resources :posts do
    resources :comments
  end

end

app/models/ability.rb
class Ability
include CanCan::Ability

    def initialize(user)
        if user.has_role? :admin
            can :manage, :all
        else
            can :read, :all
    end

  end
end

# Define abilities for the passed in user here. For example:
#
#   user ||= User.new # guest user (not logged in)
#   if user.admin?
#     can :manage, :all
#   else
#     can :read, :all
#   end
#
# The first argument to `can` is the action you are giving the user 
# permission to do.
# If you pass :manage it will apply to every action. Other common actions
# here are :read, :create, :update and :destroy.
#
# The second argument is the resource the user can perform the action on. 
# If you pass :all it will apply to every resource. Otherwise pass a Ruby
# class of the resource.
#
# The third argument is an optional hash of conditions to further filter the
# objects.
# For example, here the user can only update published articles.
#
#   can :update, Article, :published => true
#
# See the wiki for details:
# https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/comment.rb
class Comment
	include Mongoid::Document
	include Mongoid::Timestamps
	field :text, type: String
	belongs_to :user
	belongs_to :post
	validates_presence_of :text
	validates_length_of :text, :maximum => 100
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String
  field :caption, type: String
  rolify
  resourcify
  validates_length_of :title, :maximum => 30
  validates_length_of :caption, :maximum => 100
  validates_presence_of :caption
  validates_presence_of :title
  belongs_to :user
  has_many :comments

end

app/models/role.rb
class Role
  include Mongoid::Document
  has_and_belongs_to_many :users
  belongs_to :resource, :polymorphic => true
  
  field :name, :type => String

  index({
    :name => 1,
    :resource_type => 1,
    :resource_id => 1
  },
  { :unique => true})
  
  scopify
end

app/models/user.rb
class User
  include Mongoid::Document
  has_many :posts
  has_and_belongs_to_many :roles
  rolify
  # resourcify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  #attr_accessible :admin, :email, :password, :password_confirmation, :remember_me

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time


  def add_admin(user)
    if self.has_role? :admin
      true
    else
      false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource)
    # return the path based on resource
  end

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to root_url
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		@comments = Comment.all
	end

	def show
	end

	def new
		if current_user
			@user = User.find(current_user)
			@post = Post.find(params[:post_id])
			@comment = Comment.new
		else
			redirect_to new_user_session
		end
	end

	def edit
		@comment = Comment.find(params[:id])
	end

	def create
		@post = Post.find(params[:post_id])
		@user = current_user
		@comment = @post.comments.new(comment_params)
		@comment.user = @user
		if @comment.save
			redirect_to post_path(@post)
		else 
			render 'new'
		end
	end

	def update
	end

	def destroy
		Comment.find(params[:id]).destroy
		redirect_to :back
	end

private

	def set_comment
		@comment = Comment.find(params[:id])
	end

	def comment_params
		params.require(:comment).permit(:text)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	def index
    	@posts = Post.all.reverse
    	@user = current_user
	end

	def show
		@post = Post.find(params[:id])
		@comments = @post.comments.reverse
	end

	def new
		@user = current_user
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user = current_user
		if @post.save
			flash[:notice] = 'Post was successfully created.'
			redirect_to posts_path
		else
			render 'new'
		end
	end


	def edit
		@post = Post.find(params[:id])
		@user = current_user
		@comment = Comment.find(params[:id])
	end

	def update
	    @post = Post.find(params[:id])
	    if @post.update(post_params)
	      flash[:notice] = 'Post was successfully updated.'
	      redirect_to post_path(@post)
	    else
	      render 'edit'
	    end
	end

	def destroy
    @post = Post.find(params[:id])
    if (@post.user == current_user)
      @post.destroy
      redirect_to posts_path
    else
      redirect_to posts_path
	 	end
	end

private
 
	def post_params
    params.require(:post).permit(:title, :caption)
	end
	
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.excludes(:id => current_user.id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created User." 
      redirect_to root_path
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated User."
      redirect_to root_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "Successfully deleted User."
      redirect_to root_path
    end
  end 
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@users = User.all
  end

  # def show
  # 	@users = User.all
  # end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/new.html.erb
<div class="comment_container">
	<h1>Add A Comment</h1>
	<%= bootstrap_form_for([@post, @comment]) do |f| %>
		<%= f.text_field :text, placeholder: "Max. 100 Characters", class: "form-control input-lg" %>
		<div class="buttons">
		<%= f.submit class: "btn btn-primary btn-lg", value: "Submit"%> 
		</div>
	<% end %>
</div>

app/views/posts/_form.html.erb
<%= bootstrap_form_for(@post) do |f| %>
	<%= f.text_field :title, placeholder: "Max. 30 Characters" %><br />
	<%= f.text_area :caption, placeholder: "Max. 100 Characters" , size: '10x3'%><br />
<%= f.submit class: "btn btn-primary btn-lg", value: "Submit" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit your post</h1>



<%= render partial: "form" %>

app/views/posts/index.html.erb
<div class="index_post_container">
    <h1 class="index_post_header">Post Index</h1>
    <h4 class="index_post_count"><%= pluralize(@posts.count, "post") %></h4>
    <ul>
    <% @posts.each do |p| %>
            <div class=".col-md-4 posts_container">
                <li>
                    <%= link_to post_path p do %>
                        <strong> <%= p.title %> </strong> <br />
                    <% end %> 
                    <h5> Posted by <%= p.user.email %> <%= distance_of_time_in_words_to_now(p.created_at) + " ago" %> </h5>
                    
                </li>
            </div> 
    <% end %>
    </ul>
</div>

app/views/posts/new.html.erb
<div class=".col-xs-12 container-fluid">
	<h1 class="new_post_header">New Post</h1>


<%= render partial: "form" %>
</div>

app/views/posts/show.html.erb
<div class="show_post_container">
	<div class="post_container">
		<h1><%= @post.title %></h1>
		<h4><%= @post.caption %></h4>
		<div class="comments_container">
			<p> <strong>Comments</strong> </p>
			<% @post.comments.each do |c| %>
				<%= c.text %> <br /><br />
				<% if current_user %>
					<%= link_to 'Edit Post', edit_post_path, class: "btn btn-xs btn-success", type: "button" %> <br /><br />
				<% end %>
				Posted by <%= link_to c.user.email, c.user %> <%= distance_of_time_in_words_to_now(c.created_at) + " ago" %> 
				<% if current_user.has_role? :admin %>
					<%= link_to "Edit Comment", edit_post_comment_path(@post, c), class: "btn btn-xs btn-info", type: "button"  %>
					<%= link_to "Delete Comment", post_comment_path(@post, c), class: "btn btn-xs btn-danger", type: "button",  method: :delete, data: { confirm: 'Are you sure?' }  %> <br /> 
				<% end %>   
				
			<% end %>
		</div>
	</div>
</div> <br />
<div class="buttons">
	<%= link_to "Comment", new_post_comment_path(@post), class: "btn btn-lg btn-success", type: "button" %>
</div>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/show.html.erb
<p>User: <%= @user.email %></p>
<% if current_user.has_role? :admin %>
<h1>You're An Admin!</h1>
<% end %>

app/views/welcome/index.html.erb
<div class="welcome_container">
	<h1>Welcome</h1>
</div>

app/views/welcome/show.html.erb
 




        <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <%= link_to "Test", root_path, :class => "navbar-brand" %>
            <!-- <a class="navbar-brand" href="posts#index">Test</a> -->
        </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><a href="welcome#index">Hello <strong><%= current_user.email %></strong>!</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li> <%= link_to 'Create Post', new_post_path,  :class => 'navbar-link' %></li>
                        <li> <%= link_to 'View Posts', posts_path,  :class => 'navbar-link' %></li>
                        <li class="divider"></li>
                        <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                        <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                    </ul>
                </li>
            <% else %>      
                <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
                <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
            <% end %>   
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>